BesselBasis_trainable: true
PolynomialCutoff_p: 12
_jit_bailout_depth: 2
_jit_fuser: fuser1
_jit_fusion_strategy:
- !!python/tuple
 - DYNAMIC
 - 3
allow_tf32: true
append: true
avg_num_neighbors: 56.78007291666667
batch_size: 1
chemical_symbols:
- H
- O
code_commits:
 allegro: f547aa6ced349b0000f328e593d539bb1fa0d3e0
 nequip: 0b02c41cbd30ef9a2f58d95cc3dd41a8beb0ff5d
dataloader_num_workers: 0
dataset: ase
dataset_AtomicData_options:
 r_max: 6.5
dataset_file_name: /mnt/public/tgmaxson/MB-Pol/datasets/1-train.traj
dataset_seed: null
dataset_statistics_stride: 1
default_dtype: float64
device: cuda
e3nn_version: 0.5.1
early_stopping: null
early_stopping_kwargs: null
early_stopping_lower_bounds:
 LR: 1.0e-08
edge_eng_mlp_latent_dimensions:
- 64
edge_eng_mlp_nonlinearity: null
ema_decay: 0.999
ema_use_num_updates: true
embed_initial_edge: true
end_of_batch_callbacks: []
end_of_epoch_callbacks: []

end_of_train_callbacks: []
env_embed_mlp_latent_dimensions: []
env_embed_mlp_nonlinearity: null
env_embed_multiplicity: 64
equivariance_test: false
exclude_keys: - magmom - dipole
final_callbacks: []
global_rescale_scale: dataset_total_energy_std
gpu_oom_offload: false
grad_anomaly_mode: false
init_callbacks: []
initial_model_state: models/train
 -1
 -2
 -5.5
 -F2/best_model.pth
irreps_edge_sh: 1x0e+1x1o+1x2e
l_max: 2
latent_mlp_latent_dimensions: - 64 - 64 - 64
latent_mlp_nonlinearity: silu
latent_resnet: true
learning_rate: 0.0005
log_batch_freq: 1
log_epoch_freq: 1

loss_coeffs:
 forces:
  -1
  - PerSpeciesL1Loss
 stress: 50
 total_energy:
  - 20
  - PerAtomL1Loss
lr_scheduler_factor: 0.9
lr_scheduler_kwargs:
 cooldown: 0
 eps: 1.0e-08
 factor: 0.9
 min_lr: 0
 mode: min
 patience: 400
 threshold: 0.0001
 threshold_mode: rel
 verbose: false
lr_scheduler_name: ReduceLROnPlateau
lr_scheduler_patience: 400

max_epochs: 50000
max_gradient_norm: .inf
metrics_components:
  - - forces 
    - mae
    - PerSpecies: true
    - report_per_component: false

  - - forces
    - rmse
    - PerSpecies: true
    - report_per_component: false

  - - total_energy
    - mae
    - PerAtom: true

  - - total_energy
    - rmse
    - PerAtom: true

  - - stress
    - mae

  - - stress
    - rmse

metrics_key: validation_loss
model_builders: 
  - allegro.model.Allegro 
  - PerSpeciesRescale 
  - StressForceOutput 
  - RescaleEnergyEtc 
  - initialize_from_state

model_debug_mode: false
model_dtype: float32
n_train: 3200
n_train_per_epoch: null
n_val: 500
nequip_version: 0.6.0
nonscalars_include_parity: true
num_basis: 8
num_layers: 2
num_types: 2

optimizer_kwargs:
 amsgrad: false
 betas: !!python/tuple
 - 0.9
 - 0.999
 capturable: false
 differentiable: false
 eps: 1.0e-08
 foreach: null
 fused: null
 maximize: false
 weight_decay: 0
optimizer_name: Adam

parity: o3_full
per_species_rescale_scales: dataset_per_atom_total_energy_std
per_species_rescale_shifts: dataset_per_atom_total_energy_mean
r_max: 5.5
report_init_validation: true
root: models
run_name: train-1-2-5.5-E
save_checkpoint_freq: -1
save_ema_checkpoint_freq: -1
seed: 12345
shuffle: true
tensorboard: false
torch_version: !!python/object/new:torch.torch_version.TorchVersion
- 2.0.0

